Feature auc task
yongdai/quelcode_cakephp_book pull request #4
Opened 2020-06-16 16:27 UTC by yongdai

CakePHP課題２の実装を完了しましたので、レビューをお願い致します。

詳細設計書
https://docs.google.com/document/d/1Tt6uABH04GRty2tCjq1Y9e04ho--DjQ0wvfTAhJ7DSo/edit?usp=sharing

データベース定義書
https://docs.google.com/spreadsheets/d/1zvosqX5Rpq1df_PIB6-fC4jZ8bC2jYQoir4H1qfQofI/edit?usp=sharing

2020-06-18 04:59 UTC, himaru-jp requested changes

2020-06-18 04:59 UTC, himaru-jp commented on html/mycakephpapp/src/Controller/AuctionController.php
> +            if ($this->Auth->user('id') === $biditem->user->id | $this->Auth->user('id') === $biditem->bidinfo->user->id) {
```|```だとビット演算になります。
明確な理由がない場合は、```||```を用いてください。

今回はビットもしくはビットに型変換できるものなのでエラーになりませんが、
```if ($hoge | $fuga) {```のような式を書くとエラーになる可能性があります。
※$hogeが文字列だった場合など

2020-06-18 04:59 UTC, himaru-jp commented on html/mycakephpapp/src/Controller/AuctionController.php
> +        }
256行目以降のelseif内でしか使用していないため、elseif内で実行をお勧めします。
また、```$rating = $record_check;```は意図が分かりづらいため、再考をお願いします。

2020-06-18 04:59 UTC, himaru-jp commented on html/mycakephpapp/src/Controller/UsersController.php
> +        foreach($seller_rating as $value) {
できるだけ```$value```のような曖昧な変数名は避けるべきです。

2020-06-18 04:59 UTC, himaru-jp commented on html/mycakephpapp/src/Controller/UsersController.php
> +            $seller_rating_avg = $seller_rating_sum;
(修正不要)
$seller_rating_sumともに0で初期化しておいた方が分かりやすいと思います

2020-06-18 04:59 UTC, himaru-jp commented on html/mycakephpapp/src/Controller/UsersController.php
> +        $seller_rating_count = $this->Ratings->find('all')->where(['seller_id' => $id])->count();
$seller_ratingをcount関数で行数を取得すれば、DBへの接続を減らすことができます

2020-06-18 05:02 UTC, himaru-jp commented on html/mycakephpapp/src/Controller/AuctionController.php
> +        if ($biditem->finished == 1 and !empty($biditem->bidinfo->user->id)) {
厳密比較で実装をお願いします。
andではなく```&&```が一般的に使われます。

2020-06-18 05:05 UTC, himaru-jp reviewed
PHPの閉じタグは不要です。
また、最後の行に改行を入れてください。

2020-06-18 06:31 UTC, yongdai commented on html/mycakephpapp/src/Controller/AuctionController.php
> +            if ($this->Auth->user('id') === $biditem->user->id | $this->Auth->user('id') === $biditem->bidinfo->user->id) {
修正いたしました。

2020-06-19 02:48 UTC, yongdai commented on html/mycakephpapp/src/Controller/AuctionController.php
> +        }
こちら、Viewの方で、取得した$rating->seller_ratingを表示の出し分けにしようしているため、elseif内に入れてしまうと表示側の条件分岐がされずに評価内容が非表示となってしまいます。
一旦、修正せずにそのままとしています。また$rating = $record_checkとしているのはレコードがなかったときは、生成しているEntityを登録用にそのまま使うため、同じ変数に代入する形にしています。後の処理で$ratingを利用するため。

2020-06-19 02:52 UTC, yongdai commented on html/mycakephpapp/src/Controller/AuctionController.php
> +        }
処理の目的がわかりずらいため、レコードチェックには$this->find()-count()を利用して、レコードがある場合のみ$this->find()->first()を利用してEntityを取得して明示するように変更しました。

2020-06-19 02:56 UTC, yongdai commented on html/mycakephpapp/src/Controller/UsersController.php
> +        foreach($seller_rating as $value) {
修正いたしました。

2020-06-19 02:57 UTC, yongdai commented on html/mycakephpapp/src/Controller/UsersController.php
> +            $seller_rating_avg = $seller_rating_sum;
コメントありがとうございます。確かにそうですね。次回意識したいと思います。

2020-06-19 04:03 UTC, yongdai commented on html/mycakephpapp/src/Controller/AuctionController.php
> +        if ($biditem->finished == 1 and !empty($biditem->bidinfo->user->id)) {
修正いたしました。

2020-06-19 04:04 UTC, yongdai commented
> PHPの閉じタグは不要です。
> また、最後の行に改行を入れてください。

修正いたしました。

2020-06-19 08:38 UTC, Yuzunoha commented
このブランチでsqlを流しました。
コントローラのリダイレクト設定の問題か、ユーザを作成して、そのユーザでオークションアプリにログインができません。
ユーザを作成してログインできるように動作確認を願えますでしょうか。

2020-06-19 09:42 UTC, Yuzunoha commented
AuctionBaseController の logout メソッドにタイポがありますね

![image](https://user-images.githubusercontent.com/22877094/85119291-7a7d7880-b25c-11ea-8ac9-b649e6c05692.png)

2020-06-19 23:28 UTC, yongdai commented
> AuctionBaseController の logout メソッドにタイポがありますね
> 
> ![image](https://user-images.githubusercontent.com/22877094/85119291-7a7d7880-b25c-11ea-8ac9-b649e6c05692.png)

AuctionBaseControllerのlogoutメソッドのTypo修正いたしました。

2020-06-22 02:40 UTC, Yuzunoha commented on html/mycakephpapp/src/Model/Table/RatingsTable.php
> +        $rules->add($rules->existsIn(['id', 'seller_id'], 'Users'));
(discordで共有済)
これだと `buyer_idとseller_idをそれぞれUsersテーブルに主キーとして存在する値に制限する` という風に出来ていないですね><

2020-06-24 10:50 UTC, himaru-jp requested changes

2020-06-24 10:50 UTC, himaru-jp commented on html/mycakephpapp/src/Controller/AuctionController.php
> +        }
225行目の
```
        $rating = $this->Ratings->newEntity();
```
を消して、以下のようにしてもいいかもしれませんね。
```suggestion
        $rating = $this->Ratings->find('all')
            ->where(['bidinfo_id' => $biditem->bidinfo->id])->first();
        // まだ評価されていない場合
        if (!$rating) {
            $rating = $this->Ratings->newEntity();
        }
```
また、
```
//評価ががすでにある場合はViewにその評価内容を渡す
```
とコメントしてしまうと、表示以外の用途(上書き)があるため誤解を招くと思います。

2020-06-24 10:50 UTC, himaru-jp commented on html/mycakephpapp/src/Controller/AuctionController.php
> +            }
(動作検証していません)再取得せずに以下のように書くこともできそうです。
```suggestion
            // 送信されたフォームで$ratingsを更新
            $rating_new = $this->Ratings->patchEntity($rating, $this->request->getData('Ratings'));
            // Ratingsを保存
            if ($this->Ratings->save($rating_new)) {
                $rating = $rating_new;
                // 成功時のメッセージ
                $this->Flash->success(__('保存しました。'));
            } else {
                $this->Flash->error(__('保存に失敗しました。もう一度入力下さい。'));
            }
```

2020-06-24 10:50 UTC, himaru-jp commented on html/mycakephpapp/src/Controller/UsersController.php
> +        foreach($seller_rating_array as $seller_ratings) {
$seller_ratingsだと配列を想像します。再考をお願いします。
127行目の$seller_ratingや129行目のseller_rating_arrayをから変えるといいかもしれません。

2020-06-24 10:50 UTC, himaru-jp commented on html/mycakephpapp/src/Controller/AuctionController.php
> +        if ($biditem->finished === true && !empty($biditem->bidinfo->user->id)) {
```!empty()```のように否定の否定は、特別な理由がない限り可読性を下げるので避けましょう

2020-06-24 10:50 UTC, himaru-jp commented on html/mycakephpapp/src/Model/Table/RatingsTable.php
> +        $rules->add($rules->existsIn(['id', 'seller_id'], 'Users'));
この部分、不要になったのであれば削除をお願いします。

2020-06-25 16:18 UTC, yongdai commented on html/mycakephpapp/src/Model/Table/RatingsTable.php
> +        $rules->add($rules->existsIn(['id', 'seller_id'], 'Users'));
こちら削除いたしました。

2020-06-25 16:56 UTC, yongdai commented on html/mycakephpapp/src/Controller/AuctionController.php
> +        }
ご指摘いただいたようにnewEntity()を読んでいる部分が実際に使われているコード部分と離れているため可読性が悪いこと、また、冗長なコードになってしまっているため、ご提案いただいた内容をよく理解した上で修正いたしました。

2020-06-25 17:00 UTC, yongdai commented on html/mycakephpapp/src/Controller/AuctionController.php
> +            }
DBへのアクセスを減らすことができますね。ご指摘いただきました内容を理解した上で修正しました。

2020-06-26 03:41 UTC, yongdai commented on html/mycakephpapp/src/Controller/UsersController.php
> +        foreach($seller_rating_array as $seller_ratings) {
修正いたしました。Arrayで返る方をratingsとして、ループないをratingに変更しています。

2020-06-26 03:58 UTC, yongdai commented on html/mycakephpapp/src/Controller/AuctionController.php
> +        if ($biditem->finished === true && !empty($biditem->bidinfo->user->id)) {
issset()を使うように変更しました。

2020-06-26 05:04 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-06-26 05:04 UTC, piasoratech commented on html/mycakephpapp/src/Controller/AuctionController.php
> +            if ($this->Ratings->save($rating_new)) {
`$rating_new`が定義されていません。
動作確認は問題なかったでしょうか？

2020-06-26 05:12 UTC, yongdai commented on html/mycakephpapp/src/Controller/AuctionController.php
> +            if ($this->Ratings->save($rating_new)) {
すみません。Push漏れでした・・・。誕生日Boozが効いていたみたいです。

2020-06-26 05:29 UTC, piasoratech approved these changes
OKです！
次に進みましょう！

2020-06-26 14:42 UTC, merged